
spring:
  datasource:
    dynamic:
      primary: db1
      datasource:
        db1:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://172.17.172.160:5432/portal?currentSchema=public
          username: postgres
          password: 123456
        db2:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://172.17.172.160:5432/npi-pss?currentSchema=public
          username: postgres
          password: 123456
      durid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl